title: Hala Abueideh # your name (or website title) here
logo: "/images/20468.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data enthusiast with a diverse background and a passion for uncovering hidden relationships.
  I enjoy delving into the complexities of data analysis and connecting dots across various fields.
  When I'm not immersed in data, you will probably find me in the kitchen. 
  I am eager to share my experiences, insights, and recipes as you embark on my data-filled adventure, infused with creativity and fun. 
  <br><br>
  <a href="https://www.linkedin.com/in/hala-abueideh">LinkedIn Profile</a>   <br>
  <a href="mailto:hala.abueideh@gmail.com">Email</a>  <br>
  <a href="https://drive.google.com/file/d/1_Zx8s5CLe6oQzjsIouhUEnGr5LeDXSCA/view?usp=share_link"> View Resume</a>   <br>
 
    <br><br>
    <br>
#theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
