title: Hala Abueideh # your name (or website title) here
logo: "/images/20468.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data enthusiast with a diverse background and a passion for uncovering hidden relationships.
  I enjoy delving into the complexities of data analysis and connecting dots across various fields.
  When I'm not immersed in data, I find joy in cooking, viewing it as a blend of art and science. 
  I am eager to share my experiences, insights, and recipes as you embark on my data-filled adventure, infused with creativity and fun. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/hala-abueideh">View My LinkedIn Profile</a>  <br><br>
  <a href="mailto:hala.abueideh@gmail.com">Email me</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
